### ISSUE TITLE
This add-on is not available on your platform.

### ISSUE THREAD

**Issue by fjmk** [Oktavilla/fontanello#1]
The title is what I get at https://addons.mozilla.org/en-US/firefox/addon/fontanello/

Platform: Ubuntu 16.06
Firefox version: 58.0 - 64 bit

**Comment by lokesh-krishna** [comment]
Get the same message.  

Platform: Arch Linux
Firefox 60.0a1

**Comment by frederfred** [comment]
Fontanello for Firefox is supported on Linux now 🎉
