### ISSUE TITLE
Add letter-spacing to information

### ISSUE THREAD

**Issue by simube** [Oktavilla/fontanello#7]
It would be nice to have letter-spacing as information as well. great AddOn!

**Comment by frederfred** [comment]
@simube thanks!

I'm currently running a branch of this tool with that information included. I haven't decided yet whether to push it to master or not. It's a property that is rarely used, but I agree that it's nice to have it displayed when it's applied.

Please try the branch out locally if you know how, and have time: https://github.com/Oktavilla/fontanello/tree/more-css-props

99.99% of the times while surfing the web, the value will just be `normal`.

**Comment by simube** [comment]
perhaps only show it, when it is not "normal" ? Thanks, I'll try this!

**Comment by frederfred** [comment]
Unfortunately, thats not possible. Chrome requires you to setup all the menu items when the extension is initialized. The only thing I can modify after that is the content of those menu items.

One potential solution is to put a separator between the current styles and the "more props"-ones. Maybe behind a sub menu even. I'll think about it.

I'll leave this issue open until I have reached a conclusion.

**Comment by frederfred** [comment]
I just published a new version on the Chrome store (and have a pending update for the Firefox add-on (waiting for review)) that includes letter-spacing and some other props as well.

Happy Fontanello'ing!
