### ISSUE TITLE
Odd result

### ISSUE THREAD

**Issue by blackpleather** [Oktavilla/fontanello#8]
## Expected behavior
Give proper font name

## Actual behavior
At http://cdm.link/ the blog headlines are called 'S' font and blogposts are called 'M' font.

## Steps to reproduce the problem

  1. Go to http://cdm.link/
  2. Use Fontanello on fonts on page.
  3. Be sad.

## Specifications

  - Version: 1.01 (latest)
  - OS: macOS 10.14.3 (latest)
  - Browser: Chome 73.0.3683.75

**Comment by frederfred** [comment]
This is related to https://github.com/Oktavilla/fontanello/issues/6.

Fontanello does not display the name of the rendered font, but shows the `font-family` value that the developer put in their code. The names were obfuscated in this case.

Anyway, if you are curious about these specific fonts:
`S`: https://www.grillitype.com/typeface/gt-sectra
`M`: https://www.milieugrotesque.com/typefaces/maison_neue/subfamilies/1157
`P` (used in tags etc): https://www.grillitype.com/typeface/gt-pressura

Glad you are using the tool and took the time to report this 😀
